% Add exchange reactions from models generated by the individual reconstruction
% approaches to the final root consensus models.

% paths
model_dir = fullfile('data', 'models');
consensus_model_file = fullfile(model_dir, 'consensus',...
    'Root_consensus_models_biomass.mat');
ind_appraoches_model_files = {...
    fullfile(model_dir, 'kbase', 'Root', 'Root_models_genes_translated.mat'),...
    fullfile(model_dir, 'raven', 'HMMer10E-50', 'Root_converted.mat'),...
    fullfile(model_dir, 'carveme', 'Root', 'Root_models.mat'),...
    fullfile(model_dir, 'aureme', 'Root', 'Root_models_genes_translated.mat')};

% load consensus model (this will take a while)
load(consensus_model_file, 'merged_models')

% loop over individual appraoches and add original exchange reactions to
% the consensus models of the corresponding OTUs
for i = 1:numel(ind_appraoches_model_files)
    
    fprintf('Processing file %s\n', ind_appraoches_model_files{i})
    
    % load all individual models
    load(ind_appraoches_model_files{i}, 'models')
    
    for j = 1:numel(models)
        
        % find indices of exchange reactions (alternatively use findExcRxns function
        % from the COBRA toolbox)
        exc_rxns = logical(findExchangeReactions(models{j}));
        
        % add exchange reactions to consensus model
        for k = find(exc_rxns)
            rxn_id = models{j}.rxns{k};
            rxn_formula = printRxnFormula(models{j}, rxn_id, 0);
            % some exchange reactions were kept, so addReaction would throw
            % a warning and update the reaction
            if ~ismember(merged_models{j}.rxns, rxn_id)
                merged_models{j} = addReaction(merged_models{j}, rxn_id,...
                    'reactionFormula', char(rxn_formula));
            end
        end
    end
end
